extends:
  - eslint:recommended
  - angular
  - plugin:requirejs/recommended

settings:
  angular: 2

plugins:
  - requirejs

rules:
  angular/service-name: off
  angular/controller-as: off
  angular/angularelement: off
  angular/di:
    - 2
    - array

env:
  amd: true
  browser: true
  jquery: true

globals:
  requirejs: true
